import { chromium } from "playwright";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import type { SiteReport } from "../types/report.ts";

/**
 * Generates a PDF report from a SiteReport and saves it to outputPath.
 * Launches a headless Chromium, renders HTML, and exports to PDF.
 */
export async function generatePdf(report: SiteReport, outputPath: string): Promise<void> {
  await mkdir(dirname(outputPath), { recursive: true });

  const html = buildHtml(report);

  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });
    const pdfBuffer = await page.pdf({
      format: "A4",
      margin: { top: "20mm", right: "15mm", bottom: "20mm", left: "15mm" },
      printBackground: true,
    });
    await writeFile(outputPath, pdfBuffer);
  } finally {
    await browser.close();
  }
}

function buildHtml(report: SiteReport): string {
  const { meta, summary, sharedIssues, pages } = report;
  const scoreStr = computeScoreStr(summary);
  const date = new Date(meta.generatedAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const impactOrder = ["critical", "serious", "moderate", "minor"] as const;
  const impactColor: Record<string, string> = {
    critical: "#dc2626",
    serious: "#ea580c",
    moderate: "#d97706",
    minor: "#2563eb",
  };

  const issueRows = pages
    .filter(p => p.issues.length > 0)
    .slice(0, 10)
    .flatMap(p =>
      p.issues.slice(0, 5).map(issue =>
        `<tr>
          <td style="color:${impactColor[issue.impact]};font-weight:600">${escHtml(issue.impact)}</td>
          <td>${escHtml(issue.rule)}</td>
          <td style="font-size:11px;color:#555">${escHtml(p.url)}</td>
          <td style="font-size:11px">${escHtml(issue.description)}</td>
        </tr>`
      )
    )
    .join("");

  const sharedSection = sharedIssues.length > 0 ? `
<h2>Shared Issues (${sharedIssues.length} template-level issues)</h2>
<table>
  <thead><tr><th>Rule</th><th>Pages affected</th><th>Fix available</th></tr></thead>
  <tbody>
  ${sharedIssues.map(s => `<tr>
    <td>${escHtml(s.rule)}</td>
    <td>${s.pageCount}</td>
    <td>${s.suggestedFix ? "Yes" : "No"}</td>
  </tr>`).join("")}
  </tbody>
</table>` : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, Arial, sans-serif; font-size: 13px; color: #111; line-height: 1.5; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin: 24px 0 12px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
  .meta { color: #555; font-size: 12px; margin-bottom: 24px; }
  .score { display: inline-block; font-size: 48px; font-weight: 700; color: ${scoreColor(summary)}; }
  .score-label { font-size: 13px; color: #555; margin-left: 8px; }
  .stats { display: flex; gap: 24px; margin: 16px 0; flex-wrap: wrap; }
  .stat { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 12px 16px; min-width: 100px; }
  .stat-value { font-size: 24px; font-weight: 700; }
  .stat-label { font-size: 11px; color: #555; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 12px; }
  th { background: #f3f4f6; text-align: left; padding: 8px; border-bottom: 2px solid #e5e7eb; }
  td { padding: 7px 8px; border-bottom: 1px solid #f0f0f0; vertical-align: top; }
  tr:nth-child(even) td { background: #fafafa; }
  .footer { margin-top: 32px; font-size: 11px; color: #999; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style>
</head>
<body>
<h1>Accessibility Audit Report</h1>
<p class="meta">${escHtml(meta.baseUrl)} &middot; WCAG ${meta.wcagLevel} &middot; ${date} &middot; ${meta.totalDurationSeconds}s</p>

<div>
  <span class="score">${scoreStr}</span>
  <span class="score-label">/100 WCAG Score</span>
</div>

<h2>Summary</h2>
<div class="stats">
  <div class="stat">
    <div class="stat-value">${summary.totalPages}</div>
    <div class="stat-label">Pages analyzed</div>
  </div>
  <div class="stat">
    <div class="stat-value">${summary.totalIssues}</div>
    <div class="stat-label">Total issues</div>
  </div>
  ${impactOrder.map(level => `
  <div class="stat">
    <div class="stat-value" style="color:${impactColor[level]}">${summary.issuesByImpact[level]}</div>
    <div class="stat-label">${level.charAt(0).toUpperCase() + level.slice(1)}</div>
  </div>`).join("")}
</div>

<h2>Issues (sample — first 10 pages, 5 issues each)</h2>
<table>
  <thead>
    <tr><th>Impact</th><th>Rule</th><th>Page</th><th>Description</th></tr>
  </thead>
  <tbody>${issueRows}</tbody>
</table>

${sharedSection}

<div class="footer">
  Generated by a11y-crawler v${meta.toolVersions.crawler} &middot; axe-core ${meta.toolVersions.axeCore} &middot; ${meta.totalDurationSeconds}s total
</div>
</body>
</html>`;
}

function scoreColor(summary: SiteReport["summary"]): string {
  const critical = summary.issuesByImpact.critical ?? 0;
  const total = summary.totalIssues;
  if (critical > 0 || total > 50) return "#dc2626";
  if (total > 20) return "#ea580c";
  if (total > 5) return "#d97706";
  return "#16a34a";
}

function computeScoreStr(summary: SiteReport["summary"]): string {
  if (summary.totalPages === 0) return "N/A";
  const totalPenalty =
    (summary.issuesByImpact.critical ?? 0) * 10 +
    (summary.issuesByImpact.serious ?? 0) * 5 +
    (summary.issuesByImpact.moderate ?? 0) * 2 +
    (summary.issuesByImpact.minor ?? 0) * 1;
  return String(Math.max(0, Math.round(100 - totalPenalty / summary.totalPages)));
}

function escHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
