#import "theme.typ": *

#let data = json(sys.inputs.datafile)

#let fail-count = data.complianceTable.filter(r => r.status == "fail").len()
#let pass-count = data.complianceTable.filter(r => r.status == "pass").len()

#section-heading("Conclusions")

The accessibility analysis of *#data.meta.baseUrl* identified *#str(data.score.totalIssues) issues* across #str(data.score.totalPages) analyzed pages. Of the #str(data.complianceTable.len()) WCAG 2.2 criteria evaluated, *#str(fail-count) fail* and #str(pass-count) pass.

To achieve full WCAG 2.2 Level AA conformance, the identified issues must be addressed. Priority should be given to critical and serious findings, which directly block access for users with disabilities.

#v(12pt)

#section-heading("Analyzed URLs")

#table(
  columns: (1fr, auto),
  fill: (_, y) => if calc.odd(y) { gray-100 } else { white },
  table.header([*URL*], [*Issues*]),
  ..data.analyzedUrls.map(u => (
    text(size: 9pt)[#u.url],
    str(u.issueCount),
  )).flatten()
)

#v(12pt)

#align(center)[
  #text(size: 9pt, fill: gray-500)[
    Report generated by a11y-crawler #data.meta.toolVersions.crawler · #data.meta.date
  ]
]
