#import "theme.typ": *

#let data = json(sys.inputs.datafile)

#page(header: none, footer: none)[
  #v(1fr)
  #align(center)[
    #text(size: 28pt, weight: "bold", fill: gray-900)[
      Accessibility Audit Report
    ]
    #v(16pt)
    #text(size: 14pt, fill: gray-500)[
      #data.meta.baseUrl
    ]
    #v(8pt)
    #text(size: 12pt, fill: gray-500)[
      WCAG #data.meta.wcagLevel · #data.meta.date
    ]
  ]
  #v(1fr)
  #align(center)[
    #text(size: 10pt, fill: gray-500)[
      Generated by a11y-crawler · #data.meta.toolVersions.crawler
    ]
  ]
]
