#import "theme.typ": *

#let data = json(sys.inputs.datafile)

#set document(
  title: "Accessibility Audit Report — " + data.meta.baseUrl,
  author: "a11y-crawler",
)

#set text(font: body-font, size: 10pt, fill: gray-900)
#set page(
  paper: "a4",
  margin: (top: 25mm, bottom: 25mm, left: 20mm, right: 20mm),
  header: context {
    if counter(page).get().first() > 1 [
      #text(size: 8pt, fill: gray-500)[
        Accessibility Audit — #data.meta.baseUrl
        #h(1fr)
        #data.meta.date
      ]
      #line(length: 100%, stroke: 0.5pt + gray-100)
    ]
  },
  footer: context [
    #line(length: 100%, stroke: 0.5pt + gray-100)
    #text(size: 8pt, fill: gray-500)[
      Generated by a11y-crawler #data.meta.toolVersions.crawler
      #h(1fr)
      Page #counter(page).display() of #counter(page).final().first()
    ]
  ],
)

#include "cover.typ"

#pagebreak()
#outline(title: "Table of Contents", indent: auto)

#pagebreak()
#include "summary.typ"

#pagebreak()
#include "findings.typ"

#pagebreak()
#include "conclusions.typ"
